import 'package:fpdart/fpdart.dart';
import 'package:mock_interview/core/entities/evaluation_result.dart';
import 'package:mock_interview/core/errors/failures.dart';
import 'package:mock_interview/core/services/network_service.dart';
import 'package:mock_interview/core/services/unified_database_service.dart';
import 'package:mock_interview/core/models/unified_interview_session.dart';
import 'package:mock_interview/core/models/mcq_question_model.dart';
import 'package:mock_interview/core/models/mcq_evaluation_model.dart';
import 'package:mock_interview/features/mcqinterviews/data/models/interview_session_model.dart';
import 'package:mock_interview/features/mcqinterviews/data/models/question_model.dart';
import '../../domain/repositories/mcq_interview_repository.dart';

/// Appwrite-powered MCQ Interview Repository Implementation
class AppwriteMcqInterviewRepositoryImpl implements InterviewRepository {
  final UnifiedDatabaseService databaseService;
  final NetworkService networkService;

  AppwriteMcqInterviewRepositoryImpl({
    required this.databaseService,
    required this.networkService,
  });

  @override
  Future<Either<Failure, InterviewSessionModel>> startInterview({
    required String userId,
    required String jobRole,
    required String difficultyLevel,
    required int numQuestions,
    required String category,
  }) async {
    if (!await networkService.isConnected) {
      return const Left(NetworkFailure('No internet connection'));
    }

    try {
      // Create unified session in Appwrite schema
      final unifiedSession = UnifiedInterviewSession(
        sessionId: '', // Will be auto-generated by Appwrite
        userId: userId,
        jobRole: jobRole,
        interviewType: 'mcq',
        difficulty: difficultyLevel,
        category: category,
        totalQuestions: numQuestions,
        timePerQuestion: 60,
        isCompleted: false,
        startedAt: DateTime.now(),
      );

      final createdSession = await databaseService.createInterviewSession(
        unifiedSession,
      );

      // Generate MCQ questions for the session
      final questions = await _generateMCQQuestions(
        createdSession.sessionId,
        jobRole,
        difficultyLevel,
        numQuestions,
        category,
      );

      // Store questions in database
      await databaseService.storeMcqQuestions(questions);

      // Convert to legacy InterviewSessionModel for compatibility
      final sessionModel = InterviewSessionModel(
        sessionId: createdSession.sessionId,
        userId: userId,
        jobRole: jobRole,
        difficulty: difficultyLevel,
        category: category,
        totalQuestions: numQuestions,
        timePerQuestion: 60,
        isCompleted: false,
        startedAt: createdSession.startedAt,
        questions:
            questions
                .map(
                  (q) => QuestionModel(
                    id: q.questionId,
                    sessionId: q.sessionId,
                    questionNumber: q.questionNo,
                    questionText: q.question,
                    options: q.options,
                    correctAnswer: q.correctAnswer,
                    explanation: q.explanation,
                    difficulty: q.difficulty,
                    category: q.category,
                    topic: q.topic,
                    jobRole: q.jobRole,
                  ),
                )
                .toList(),
      );

      return Right(sessionModel);
    } catch (e) {
      return Left(ServerFailure('Failed to start interview: ${e.toString()}'));
    }
  }

  @override
  Future<Either<Failure, EvaluationResult>> submitAnswers({
    required String sessionId,
    required String userId,
    required List<String> answers,
    required String jobRole,
    required String difficultyLevel,
    required String category,
  }) async {
    if (!await networkService.isConnected) {
      return const Left(NetworkFailure('No internet connection'));
    }

    try {
      // Get session and questions from Appwrite
      final session = await databaseService.getInterviewSession(sessionId);
      final questions = await databaseService.getMcqQuestions(sessionId);

      // Calculate score
      int correctAnswers = 0;
      final questionResults = <QuestionResult>[];

      for (int i = 0; i < questions.length && i < answers.length; i++) {
        final question = questions[i];
        final userAnswer = answers[i];
        final isCorrect = question.correctAnswer == userAnswer;

        if (isCorrect) {
          correctAnswers++;
        }

        questionResults.add(
          QuestionResult(
            questionId: question.questionId,
            questionNumber: question.questionNo,
            question: question.question,
            userAnswer: userAnswer,
            correctAnswer: question.correctAnswer,
            isCorrect: isCorrect,
            score: isCorrect ? 1 : 0,
            explanation: question.explanation,
            topic: question.topic,
            difficulty: question.difficulty,
          ),
        );
      }

      final finalScore = correctAnswers.toDouble();
      final percentage = (correctAnswers / questions.length * 100);
      final passed = percentage >= 60;

      // Create MCQ evaluation
      final evaluation = McqEvaluationModel(
        evaluationId: '',
        sessionId: sessionId,
        totalQuestions: questions.length,
        correctAnswers: correctAnswers,
        finalScore: finalScore,
        timeTaken: DateTime.now().difference(session.startedAt).inSeconds,
        createdAt: DateTime.now(),
      );

      await databaseService.storeMcqEvaluation(evaluation);

      // Update session
      final updatedSession = UnifiedInterviewSession(
        sessionId: session.sessionId,
        userId: session.userId,
        jobRole: session.jobRole,
        interviewType: session.interviewType,
        difficulty: session.difficulty,
        category: session.category,
        totalQuestions: session.totalQuestions,
        timePerQuestion: session.timePerQuestion,
        isCompleted: true,
        passed: passed,
        score: finalScore,
        percentage: percentage,
        startedAt: session.startedAt,
        completedAt: DateTime.now(),
        duration: DateTime.now().difference(session.startedAt).inSeconds,
      );

      await databaseService.updateInterviewSession(updatedSession);

      // Create EvaluationResult
      final evaluationResult = EvaluationResult(
        sessionId: sessionId,
        totalQuestions: questions.length,
        results: questionResults,
        finalScore: finalScore,
        percentage: percentage,
        passed: passed,
        sessionComplete: true,
        completedAt: DateTime.now(),
      );

      return Right(evaluationResult);
    } catch (e) {
      return Left(ServerFailure('Failed to submit answers: ${e.toString()}'));
    }
  }

  @override
  Future<Either<Failure, Map<String, dynamic>>> completeInterview({
    required String sessionId,
    required String userId,
    required int score,
    required int timeTaken,
    required int totalQuestions,
    required int correctAnswers,
  }) async {
    if (!await networkService.isConnected) {
      return const Left(NetworkFailure('No internet connection'));
    }

    try {
      final session = await databaseService.getInterviewSession(sessionId);
      final percentage = (score / totalQuestions * 100).toDouble();

      final updatedSession = UnifiedInterviewSession(
        sessionId: session.sessionId,
        userId: session.userId,
        jobRole: session.jobRole,
        interviewType: session.interviewType,
        difficulty: session.difficulty,
        category: session.category,
        totalQuestions: session.totalQuestions,
        timePerQuestion: session.timePerQuestion,
        isCompleted: true,
        passed: percentage >= 60,
        score: score.toDouble(),
        percentage: percentage,
        startedAt: session.startedAt,
        completedAt: DateTime.now(),
        duration: timeTaken,
      );

      await databaseService.updateInterviewSession(updatedSession);

      return Right({
        'success': true,
        'sessionId': sessionId,
        'score': score,
        'percentage': percentage,
        'passed': percentage >= 60,
      });
    } catch (e) {
      return Left(
        ServerFailure('Failed to complete interview: ${e.toString()}'),
      );
    }
  }

  @override
  Future<Either<Failure, Map<String, dynamic>>> getSessionStats(
    String sessionId,
  ) async {
    if (!await networkService.isConnected) {
      return const Left(NetworkFailure('No internet connection'));
    }

    try {
      final session = await databaseService.getInterviewSession(sessionId);

      return Right({
        'sessionId': sessionId,
        'totalQuestions': session.totalQuestions,
        'score': session.score ?? 0,
        'percentage': session.percentage ?? 0,
        'isCompleted': session.isCompleted,
        'passed': session.passed ?? false,
        'duration': session.duration ?? 0,
        'feedback': 'Evaluation completed successfully',
      });
    } catch (e) {
      return Left(
        ServerFailure('Failed to get session stats: ${e.toString()}'),
      );
    }
  }

  @override
  Future<Either<Failure, void>> deleteSession(String sessionId) async {
    if (!await networkService.isConnected) {
      return const Left(NetworkFailure('No internet connection'));
    }

    try {
      await databaseService.deleteInterviewSession(sessionId);
      return const Right(null);
    } catch (e) {
      return Left(ServerFailure('Failed to delete session: ${e.toString()}'));
    }
  }

  @override
  Future<Either<Failure, Map<String, dynamic>>> getActiveSessions() async {
    if (!await networkService.isConnected) {
      return const Left(NetworkFailure('No internet connection'));
    }

    try {
      return const Right({'activeSessions': [], 'count': 0});
    } catch (e) {
      return Left(
        ServerFailure('Failed to get active sessions: ${e.toString()}'),
      );
    }
  }

  @override
  Future<Either<Failure, bool>> checkHealth() async {
    if (!await networkService.isConnected) {
      return const Left(NetworkFailure('No internet connection'));
    }

    try {
      await databaseService.getUserInterviewSessions('health-check');
      return const Right(true);
    } catch (e) {
      return Left(ServerFailure('Health check failed: ${e.toString()}'));
    }
  }

  /// Generate MCQ questions for a session
  Future<List<McqQuestionModel>> _generateMCQQuestions(
    String sessionId,
    String jobRole,
    String difficultyLevel,
    int numQuestions,
    String category,
  ) async {
    final questions = <McqQuestionModel>[];

    for (int i = 0; i < numQuestions; i++) {
      final question = McqQuestionModel(
        questionId: '',
        sessionId: sessionId,
        questionNo: i + 1,
        question:
            'Sample $category question ${i + 1} for $jobRole position ($difficultyLevel difficulty)',
        options: [
          'Option A - Sample answer 1',
          'Option B - Sample answer 2',
          'Option C - Sample answer 3',
          'Option D - Sample answer 4',
        ],
        correctAnswer: 'Option A - Sample answer 1',
        explanation:
            'This is the correct answer because it demonstrates the core concept relevant to $category.',
        difficulty: difficultyLevel,
        category: category,
        topic: '$category Fundamentals',
        jobRole: jobRole,
      );

      questions.add(question);
    }

    return questions;
  }
}
